# Default configuration for city-sim

# Simulation parameters
simulation:
  days: 20
  time_steps_per_day: 8
  start_hour: 6  # Simulation starts at 6am

# Agent parameters
agents:
  count: 50
  energy_decay_rate: 0.05  # Energy decrease per time step
  hunger_increase_rate: 0.08  # Hunger increase per time step
  social_need_base_rate: 0.03  # Base social need increase rate
  
# POI parameters
pois:
  count: 20
  categories:
    - training
    - food
    - rest
    - sleep
    - office
    - armory
    - recreation
    - medical
    - fitness
    - library
    - workshop
    - communications
    - maintenance
    - outdoor
    - spiritual
    - logistics
  distribution:
    training: 0.25
    food: 0.15
    rest: 0.10
    sleep: 0.10
    office: 0.08
    armory: 0.08
    recreation: 0.06
    medical: 0.05
    fitness: 0.04
    library: 0.03
    workshop: 0.02
    communications: 0.015
    maintenance: 0.015
    outdoor: 0.01
    spiritual: 0.01
    logistics: 0.005
    
# Memory parameters
memory:
  max_temporal_size: 1000000  # Maximum number of temporal memory nodes
  reflective_summary_days: 7  # Number of days to include in reflective summary
  
# LLM parameters
llm:
  default_provider: "azure"  # Options: "gemini", "azure"
  request_timeout: 30  # Timeout in seconds